CREATE DATABASE IF NOT EXISTS ex01 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ex01;

CREATE TABLE IF NOT EXISTS registros (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  gmail VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
